### PR TITLE
[Experimental] AppHeader.vue: use a range date picker

### PR DESCRIPTION
**Pull request by Tofee**
This is a quick and dirty implementation of a range picker, to illustrate my comment https://github.com/owntracks/frontend/issues/43#issuecomment-1243020903 about date picker.

For my own use it seems to work, but it's probably not what you'd want to merge right now...

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
If you want to have this merged at the very least remove the `vue-ctk-date-time-picker` dependency :)

**Comment by Tofee** [comment]
> If you want to have this merged at the very least remove the `vue-ctk-date-time-picker` dependency :)

The change has been done, do I need to do something else to mark the requested change as "handled" ?

**Comment by Tofee** [comment]
Superseeded by https://github.com/owntracks/frontend/pull/116

**Comment by jpmens** [comment]
@Tofee thank you for your contribution, even if it has been superseded; much appreciated!

**Pull request closed without merging**
